FROM ubuntu:20.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates wget make --no-install-recommends

RUN wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2024-01-20/oss-cad-suite-linux-x64-20240120.tgz && \
	tar xf /oss-cad-suite-linux-x64-*.tgz && \
	rm -rf /oss-cad-suite-linux-x64-*.tgz

ENV PATH="/oss-cad-suite/bin:${PATH}"

CMD ["/bin/bash"]
