FROM ubuntu:24.04

ENV ALLOW_ROOT 1

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates wget sudo build-essential clang bison flex cmake git libreadline-dev gawk gfortran tcl-dev libffi-dev pkg-config python3 python3-dev libpython3-dev python3-pip python3-yaml python3-venv python3-setuptools pypy3 libboost-all-dev zlib1g-dev libeigen3-dev curl gnutls-bin openssl libfl-dev --no-install-recommends

RUN cd / && \
	wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz && \
	tar xf bison-3.8.2.tar.gz && \
	cd bison-3.8.2 && \
	./configure && \
	make -j8 && \
	make install

RUN cd / && \
	git clone https://github.com/YosysHQ/yosys.git && \
	cd yosys && \
	git checkout v0.68 && \
	git submodule update --init --recursive && \
    cmake -B build . -DCMAKE_BUILD_TYPE=Release && \
	cmake --build build --config Release --parallel $(nproc) && \
	cmake --install build --strip
#make config-gcc && \

RUN cd / && \
	git clone -b stable-backports https://github.com/openXC7/nextpnr-xilinx.git && \
	cd nextpnr-xilinx && \
    git checkout 1743d0f && \ 
	git submodule update --init --recursive && \
	cmake -DARCH=xilinx -DBUILD_GUI=0 -DCMAKE_INSTALL_PREFIX=/usr/local && \
	make -j8 && \
	make install && \
	(cp bbasm /usr/local/bin/ || true) && \
	mkdir /chipdb
#last try: 62beadc
#working: 1743d0f

RUN cd / && \
    git clone https://github.com/openXC7/prjxray.git && \
    cd prjxray && \
    git submodule update --init --recursive && \
    mkdir -p build && cd build && cmake .. && make -j$(nproc) && make install 

RUN cd /prjxray && python3 -m venv env

# prjxray python env installation problem
RUN cd /prjxray && PATH=/prjxray/env/bin:$PATH VIRTUAL_ENV=/prjxray/env pip3 install --prefix=/prjxray/env -r requirements.txt 
#RUN cd /prjxray/third_party/fasm && PATH=/prjxray/env/bin:$PATH pip3 install --prefix=/prjxray/env -r requirements.txt 
#RUN cd /prjxray/third_party/fasm && PATH=/prjxray/env/bin:$PATH python3 setup.py install --prefix=/prjxray/env --verbose --antlr-runtime=shared
# Use latest nextpnr-xilinx-meta (with zynq 7030, pcie_2_1)
RUN cd /nextpnr-xilinx/xilinx/external/nextpnr-xilinx-meta && git pull origin master && git checkout master
 #Use latest prjxray-db from regymm/openXC7 clone
#RUN cd /nextpnr-xilinx/xilinx/external/prjxray-db && \
    #git remote set-url origin https://github.com/regymm/prjxray-db.git && \
    #git fetch origin master && \
    #git checkout master && \
    #git reset --hard origin/master
ENV PYTHONPATH="/prjxray"
COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/bin/bash"]
